;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-delete-char
        backward-sexp
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        c-indent-line-or-region
        down-list
        end-of-buffer
        forward-sexp
        go-mode-insert-and-indent
        indent-region
        kill-region
        markdown-enter-key
        reindent-then-newline-and-indent
        ruby-backward-sexp
        ruby-electric-brace
        ruby-forward-sexp
        shell-command-on-region
        skk-delete-backward-char
        skk-insert
        skk-previous-candidate
        toggle-truncate-lines
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
