;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-delete-char
        backward-sexp
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        c-indent-line-or-region
        down-list
        end-of-buffer
        forward-sexp
        indent-region
        kill-region
        ruby-forward-sexp
        shell-command-on-region
        toggle-truncate-lines
        ))

(setq mc/cmds-to-run-once
      '(
        ))
