;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ac-start
        backward-delete-char
        backward-sexp
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        comint-delchar-or-maybe-eof
        comment-dwim
        delete-trailing-whitespace
        down-list
        end-of-buffer
        forward-sexp
        go-mode-insert-and-indent
        indent-for-tab-command
        indent-region
        kill-region
        markdown-enter-key
        next-line-and-recenter
        recenter
        reindent-then-newline-and-indent
        ruby-backward-sexp
        ruby-electric-brace
        ruby-forward-sexp
        ruby-indent-line
        sgml-slash
        sh-assignment
        shell-command-on-region
        skk-delete-backward-char
        skk-insert
        skk-jisx0208-latin-insert
        skk-kakutei
        skk-previous-candidate
        skk-undo
        toggle-truncate-lines
        wdired-finish-edit
        yaml-electric-bar-and-angle
        yaml-electric-dash-and-dot
        yaml-next-block
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
